import { BookText, FlaskConical, Link, Sparkles } from "lucide-react"

export const config = {
  menuData: [
    {
      text: "博客",
      path: "/posts",
      icon: BookText,
    },
    {
      text: "项目",
      path: "/project",
      icon: Sparkles,
    },
    {
      text: "链接",
      path: "/link",
      icon: Link,
    },
    // {
    //     text: '学习笔记',
    //     path: '/note'
    // },
    // {
    //     text: 'demo',
    //     path: '/demo'
    // },
    // {
    //   text: "组件测试",
    //   path: "/test",
    //   icon: FlaskConical,
    // },
  ],
  projectData: [
    {
      icon: "/logo.jpg",
      title: "个人博客",
      description: "基于Next.js构建的个人博客",
      url: "https://xiaonuo.love",
      tags: [
        {
          text: "Next.js",
          color: "stone",
        },
        {
          text: "TailwindCss",
          color: "blue",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "学习笔记",
      description: "基于vitePress构建的文档站点，记录一些知识点和常见问题",
      url: "https://xiaonuo.love",
      tags: [
        {
          text: "VitePress",
          color: "green",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "有录网模仿网站",
      description: "基于Nuxt.js构建的模仿有录网开发的网站，主要是学习用",
      url: "https://uoffer.xiaonuo.love",
      tags: [
        {
          text: "Nuxt.js",
          color: "green",
        },
        {
          text: "UnoCss",
          color: "violet",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "Bupu-admin",
      description: "基于React、Antd构建的一套后台管理模板",
      url: "https://bupu-admin.xiaonuo.love/",
      tags: [
        {
          text: "React",
          color: "indigo",
        },
        {
          text: "Antd",
          color: "blue",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "Bupu-board",
      description: "使用原生js及canvas构建的一个截屏工具以及白板",
      url: "https://bupu-board.xiaonuo.love/",
      tags: [
        {
          text: "JavaScript",
          color: "yellow",
        },
        {
          text: "Canvas",
          color: "slate",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "就业小知",
      description: "一款集成语音识别、百度地图、数字人的求职机系统",
      url: "https://xiaozhi.beikesmart.com",
      tags: [
        {
          text: "Vue3",
          color: "green",
        },
        {
          text: "讯飞数字人",
          color: "rose",
        },
        {
          text: "百度地图",
          color: "fuchsia",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "uniplat-admin",
      description: "公司用的通用后台管理网站，支持多入口模块管理",
      url: "https://xiaozhi-uniplat.beikesmart.com",
      tags: [
        {
          text: "Vue3",
          color: "green",
        },
        {
          text: "ElementPlus",
          color: "blue",
        },
      ],
      type: "个人",
    },
    {
      icon: "/logo.jpg",
      title: "即时通讯H5",
      description: "基于Vue3、Vant构建的一个即时通讯聊天软件",
      url: "http://dd.dreamdt.cn:8899/mobile/index.html#/login",
      tags: [
        {
          text: "Vue3",
          color: "green",
        },
        {
          text: "Vant",
          color: "green",
        },
      ],
      type: "个人",
    },
  ],
  linkData: [
    {
      id: 1,
      name: "build",
      label: "编译构建",
      createdAt: "2024-01-30T08:46:54.567Z",
      updatedAt: "2024-01-30T08:46:54.567Z",
      lists: [
        {
          id: 3,
          contribute: "https://github.com/docschina/parceljs.io",
          desc: "零配置打包工具",
          home: "https://parceljs.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/parcel.png",
          name: "Parcel",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 6,
          contribute: "https://github.com/vitejs/docs-cn",
          desc: "下一代前端开发与构建工具",
          home: "https://cn.vitejs.dev/",
          is_docschina: false,
          logo: "https://vitejs.dev/logo.svg",
          name: "Vite",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 4,
          contribute: "https://github.com/docschina/rollupjs.org",
          desc: "新一代 JavaScript 模块打包器",
          home: "https://rollup.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/rollup.svg",
          name: "Rollup",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 2,
          contribute: "https://github.com/docschina/webpack.js.org",
          desc: "用于现代 JavaScript 应用程序的静态模块打包工具",
          home: "https://webpack.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/webpack-offical.svg",
          name: "webpack",
          createdAt: "2024-01-30T15:32:07.215Z",
          updatedAt: "2024-01-30T15:32:07.215Z",
        },
        {
          id: 8,
          contribute: null,
          desc: "JavaScript 世界的构建工具",
          home: "https://grunt.docschina.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/grunt.svg",
          name: "Grunt",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 9,
          contribute: "https://github.com/vercel/turbo",
          desc: "webpack创始人下一代构建工具",
          home: "https://turbo.build/",
          is_docschina: false,
          logo: "https://turbo.build/images/docs/pack/turbopack-hero-logo-dark.svg",
          name: "turborepo",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 5,
          contribute: null,
          desc: "基于流的自动化构建工具",
          home: "http://www.gulpjs.com.cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/gulp.svg",
          name: "Gulp",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 1,
          contribute: "https://github.com/docschina/babeljs.io",
          desc: "一个编译工具，让你可以项目中直接使用下一代 JavaScript",
          home: "https://babel.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/babel.png",
          name: "Babel",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
        {
          id: 7,
          contribute: null,
          desc: "用于管理有多个包的 JavaScript 项目的工具",
          home: "https://lerna.js.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/lerna.svg",
          name: "Lerna",
          createdAt: "2024-01-30T15:32:07.216Z",
          updatedAt: "2024-01-30T15:32:07.216Z",
        },
      ],
    },
    {
      id: 2,
      name: "css",
      label: "CSS",
      createdAt: "2024-01-30T08:58:17.886Z",
      updatedAt: "2024-01-30T08:58:17.886Z",
      lists: [
        {
          id: 10,
          contribute: null,
          desc: "Sass 是 CSS 的一个扩展，它使 CSS 的使用起来更加优雅和强大。",
          home: "https://sass-guidelin.es/zh/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/sass.svg",
          name: "Sass",
          createdAt: "2024-01-30T15:32:07.218Z",
          updatedAt: "2024-01-30T15:32:07.218Z",
        },
        {
          id: 15,
          contribute:
            "https://github.com/docschina/postcss/blob/cn/Translation.md",
          desc: "通过 JavaScript 来转换 CSS，并且提供强大的插件系统",
          home: "http://postcss.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/postcss.svg",
          name: "PostCSS",
          createdAt: "2024-01-30T15:32:07.218Z",
          updatedAt: "2024-01-30T15:32:07.218Z",
        },
        {
          id: 13,
          contribute: null,
          desc: "富有表现力、动态、健壮的 CSS",
          home: "http://www.zhangxinxu.com/jq/stylus/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/stylus.svg",
          name: "Stylus",
          createdAt: "2024-01-30T15:32:07.218Z",
          updatedAt: "2024-01-30T15:32:07.218Z",
        },
        {
          id: 11,
          contribute: null,
          desc: "Less 是 CSS 预处理语言，使 CSS 更易维护和扩展",
          home: "http://lesscss.cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/less.svg",
          name: "Less",
          createdAt: "2024-01-30T15:32:07.218Z",
          updatedAt: "2024-01-30T15:32:07.218Z",
        },
      ],
    },
    {
      id: 3,
      name: "fronend-framework",
      label: "前端框架",
      createdAt: "2024-01-30T08:58:30.253Z",
      updatedAt: "2024-01-30T08:58:30.253Z",
      lists: [
        {
          id: 90,
          contribute: "https://github.com/vuejs/vue-next",
          desc: "渐进式 JavaScript 框架",
          home: "https://v3.cn.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vue 3",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
        {
          id: 87,
          contribute: "https://github.com/reactjs/zh-hans.reactjs.org",
          desc: "构建用户界面的 JavaScript 库",
          home: "https://react.docschina.org",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/react.svg",
          name: "React",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
        {
          id: 83,
          contribute: "https://github.com/vuejs/cn.vuejs.org",
          desc: "渐进式 JavaScript 框架",
          home: "https://cn.vuejs.org/v2/guide/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vue 2",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
        {
          id: 89,
          contribute: "https://github.com/angular/angular",
          desc: "应用程序设计框架和开发平台，用于创建高效且复杂的单页应用程序",
          home: "https://angular.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/angular.svg",
          name: "Angular",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
        {
          id: 94,
          contribute: "https://github.com/solidjs/solid",
          desc: "用于构建声明式、高效且灵活 UI 界面的 JavaScript 库。",
          home: "https://www.solidjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/solid.svg",
          name: "Solid",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
        {
          id: 91,
          contribute: "https://github.com/sveltejs/svelte",
          desc: "将声明性组件转换为精准高效更新 DOM 的 JavaScript 代码。",
          home: "https://svelte.dev/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/svelte.svg?t=1",
          name: "Svelte",
          createdAt: "2024-01-30T15:32:07.230Z",
          updatedAt: "2024-01-30T15:32:07.230Z",
        },
      ],
    },
    {
      id: 4,
      name: "lint",
      label: "代码检查",
      createdAt: "2024-01-30T08:58:47.599Z",
      updatedAt: "2024-01-30T08:58:47.599Z",
      lists: [
        {
          id: 97,
          contribute: null,
          desc: "JavaScript 风格指南、检查工具和格式化工具",
          home: "https://standardjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/standardjs.svg",
          name: "Standard JS",
          createdAt: "2024-01-30T15:32:07.231Z",
          updatedAt: "2024-01-30T15:32:07.231Z",
        },
        {
          id: 95,
          contribute: "https://github.com/docschina/stylelint",
          desc: "强大的现代 CSS 检测工具，帮助样式表遵循一致的约定和避免错误",
          home: "https://stylelint.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/stylelint.svg",
          name: "StyleLint",
          createdAt: "2024-01-30T15:32:07.231Z",
          updatedAt: "2024-01-30T15:32:07.231Z",
        },
        {
          id: 92,
          contribute: null,
          desc: "可组装的、用于 JavaScript 和 JSX 的代码检查工具",
          home: "https://cn.eslint.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/eslint.svg",
          name: "ESLint",
          createdAt: "2024-01-30T15:32:07.231Z",
          updatedAt: "2024-01-30T15:32:07.231Z",
        },
      ],
    },
    {
      id: 5,
      name: "miniprogram",
      label: "小程序",
      createdAt: "2024-01-30T08:58:58.670Z",
      updatedAt: "2024-01-30T08:58:58.670Z",
      lists: [
        {
          id: 75,
          contribute: "https://github.com/Tencent/omi",
          desc: "Omi 可以开发桌面 Web、移动 H5，同时支持开发小程序",
          home: "http://omijs.org",
          is_docschina: false,
          logo: "https://omi.cdn-go.cn/admin/latest/home/omi.svg",
          name: "omi/omip",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 77,
          contribute: "https://github.com/NervJS/taro",
          desc: "Taro 是一套遵循 React 语法规范的 多端开发 解决方案。",
          home: "https://taro.jd.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/taro.png",
          name: "Taro",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 78,
          contribute: "https://github.com/wechat-miniprogram/kbone",
          desc: "kbone 用于支持一个项目可以同时在 Web 端和小程序端被使用",
          home: "https://developers.weixin.qq.com/miniprogram/dev/extended/kbone/",
          is_docschina: false,
          logo: "https://open.weixin.qq.com/zh_CN/htmledition/res/assets/res-design-download/icon64_wx_logo.png",
          name: "kbone",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 79,
          contribute: "https://github.com/remaxjs/remax",
          desc: "Remax 将 React 运行在小程序环境中，让你可以使用完整的 React 进行小程序开发。",
          home: "https://remaxjs.org/",
          is_docschina: false,
          logo: "https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*1NHAQYduQiQAAAAAAAAAAABkARQnAQ",
          name: "Remax",
          createdAt: "2024-01-30T15:32:07.228Z",
          updatedAt: "2024-01-30T15:32:07.228Z",
        },
        {
          id: 80,
          contribute: "https://github.com/Tencent/wepy",
          desc: "WePY 是一款让小程序支持组件化开发的框架，通过预编译的手段让开发者可以选择自己喜欢的开发风格去开发小程序",
          home: "https://developers.weixin.qq.com/miniprogram/dev/extended/kbone/",
          is_docschina: false,
          logo: "https://opensource.tencent.com/img/wepy.png",
          name: "wepy",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 81,
          contribute: "https://github.com/RubyLouvre/nanachi",
          desc: "基于 React 的多端小程序转译框架，完美兼容 React 生命周期",
          home: "https://rubylouvre.github.io/nanachi/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/nanachi.png",
          name: "nanachi",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 86,
          contribute: "https://github.com/Meituan-Dianping/mpvue",
          desc: "框架基于 Vue.js 核心，mpvue 修改了 Vue.js 的 runtime 和 compiler 实现，使其可以运行在小程序环境中，从而为小程序开发引入了整套 Vue.js 开发体验。",
          home: "http://mpvue.com",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/mpvue.png",
          name: "mpvue",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 84,
          contribute: "https://github.com/wxajs/wxa",
          desc: "wxa 是一个 AOP 框架，主要使用 Decorator（运行时改写，拦截）和预编译实现框架功能。",
          home: "https://wxajs.github.io/wxa/",
          is_docschina: false,
          logo: "https://github.com/wxajs/wxa/raw/dev/wxa-logo.png",
          name: "wxa",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 82,
          contribute: "https://github.com/didi/mpx",
          desc: "Mpx 是一款致力于提高小程序开发体验的增强型小程序框架，通过 Mpx，我们能够以最先进的 web 开发体验来开发生产性能深度优化的小程序。",
          home: "https://didi.github.io/mpx/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/mpx-logo.png",
          name: "mpx",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 85,
          contribute: "https://github.com/dcloudio/uni-app",
          desc: "框架基于 Vue.js 核心，mpvue 修改了 Vue.js 的 runtime 和 compiler 实现，使其可以运行在小程序环境中，从而为小程序开发引入了整套 Vue.js 开发体验。",
          home: "https://uniapp.dcloud.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/uniapp.jpeg",
          name: "uni-app",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
        {
          id: 88,
          contribute: "https://github.com/didi/chameleon",
          desc: "Chameleon/kəˈmiːlɪən/，简写CML，中文名卡梅龙；中文意思变色龙，意味着就像变色龙一样能适应不同环境的跨端整体解决方案。",
          home: "https://cml.js.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/chameleon.png",
          name: "chameleon",
          createdAt: "2024-01-30T15:32:07.229Z",
          updatedAt: "2024-01-30T15:32:07.229Z",
        },
      ],
    },
    {
      id: 6,
      name: "node",
      label: "Node.js & Deno",
      createdAt: "2024-01-30T08:59:10.576Z",
      updatedAt: "2024-01-30T08:59:10.576Z",
      lists: [
        {
          id: 66,
          contribute: "https://github.com/demopark/koa-docs-Zh-CN",
          desc: "新一代的 Web 后台框架",
          home: "https://koajs.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/koa.svg",
          name: "Koa",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 67,
          contribute: "https://github.com/nodejscn/node-api-cn",
          desc: "基于 V8 引擎的 JavaScript 运行环境",
          home: "http://nodejs.cn/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/node.svg",
          name: "Node.js",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 69,
          contribute: "https://deno.js.cn/",
          desc: "Deno 是一个 JavaScript/TypeScript 的运行时",
          home: "https://manual.deno.js.cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/deno.svg",
          name: "Deno",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 68,
          contribute: null,
          desc: "为企业级框架和 Node.js & Koa 应用程序而生",
          home: "https://eggjs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/egg.png",
          name: "egg",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 65,
          contribute: null,
          desc: "快速极简的 Web 框架",
          home: "http://expressjs.com/zh-cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/express.png",
          name: "Express",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 72,
          contribute: null,
          desc: "淘宝提供的 npmjs.org 镜像",
          home: "https://npmmirror.com/",
          is_docschina: false,
          logo: "https://npmmirror.com/cnpm.png",
          name: "npmmirror",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 70,
          contribute: null,
          desc: "渐进式 Node.js 框架，构建高效、可靠和可扩展的 server 应用程序",
          home: "https://nestjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/nest.png",
          name: "nest",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 71,
          contribute: null,
          desc: "能够使用完整 ES6/7 特性进行开发的 Node.js 应用程序",
          home: "https://thinkjs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/think.png",
          name: "ThinkJS",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 73,
          contribute: null,
          desc: "npm 是 JavaScript package 管理工具，在这里可以找到可复用代码，并以强大的全新方式进行聚合",
          home: "https://docs.npmjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/npm.png",
          name: "npm",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 76,
          contribute: null,
          desc: "JavaScript新一代一站式运行时",
          home: "https://bun.sh/",
          is_docschina: false,
          logo: "https://bun.sh/logo.svg",
          name: "bun",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
        {
          id: 74,
          contribute: null,
          desc: "快速、可靠和安全的依赖管理",
          home: "https://yarnpkg.com/zh-Hans/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/yarn.png",
          name: "yarn",
          createdAt: "2024-01-30T15:32:07.227Z",
          updatedAt: "2024-01-30T15:32:07.227Z",
        },
      ],
    },
    {
      id: 7,
      name: "react",
      label: "React",
      createdAt: "2024-01-30T08:59:21.007Z",
      updatedAt: "2024-01-30T08:59:21.007Z",
      lists: [
        {
          id: 57,
          contribute: "https://github.com/reduxjs/redux",
          desc: "React 状态管理",
          home: "https://redux.js.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/redux.svg",
          name: "Redux",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 59,
          contribute: "https://github.com/vercel/next.js",
          desc: "React 零配置一站式解决方案",
          home: "https://nextjs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/nextjs.png",
          name: "Next.js",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 54,
          contribute: "https://github.com/facebook/create-react-app",
          desc: "React 官方维护的创建 React 单页面应用的工具",
          home: "https://create-react-app.dev/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/create-react-app.svg",
          name: "Create React App",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 58,
          contribute: "https://github.com/preactjs/preact-www",
          desc: "React 的 3kb 轻量化方案，拥有同样的 ES6 API",
          home: "https://preactjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/preact.png",
          name: "Preact",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 53,
          contribute: "https://github.com/remix-run/react-router",
          desc: "React 导航组件",
          home: "https://reactrouter.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/react-router.svg",
          name: "React-Router",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 55,
          contribute: "https://github.com/NervJS/nerv",
          desc: "Nerv 是一款基于虚拟 DOM 技术的 JavaScript（TypeScript）库，它提供了与 React 16 一致的使用方式与 API，并且拥有更高的性能表现、更小的包大小以及更好的浏览器兼容性",
          home: "https://nerv.aotu.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/nerv.png",
          name: "Nerv",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 61,
          contribute: "https://github.com/blitz-js/blitz",
          desc: "基于 Next.js 构建的全栈 React 框架，灵感来源于 Ruby on Rails，具有零 API 的数据层抽象，无需 REST/GraphQL",
          home: "https://blitzjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/blitz.svg",
          name: "Blitz",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 60,
          contribute: "https://github.com/gatsbyjs/gatsby",
          desc: "基于 React 实现构建快速、现代的应用程序及网站",
          home: "https://www.gatsbyjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/Gatsby.svg",
          name: "Gatsby",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 63,
          contribute: "https://github.com/redwoodjs/redwood",
          desc: "将全栈引入 Jamstack，基于 React、GraphQL 和 Prisma 实现",
          home: "https://redwoodjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/redwood.svg",
          name: "Redwood",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 64,
          contribute: "https://github.com/alibaba/ice",
          desc: "基于 React 的渐进式研发框架",
          home: "https://ice.work/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/icework.png",
          name: "ice.js",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
        {
          id: 62,
          contribute: "https://github.com/umijs/umi",
          desc: "插件化的企业级前端应用框架",
          home: "https://umijs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/umi.png",
          name: "UmiJS",
          createdAt: "2024-01-30T15:32:07.225Z",
          updatedAt: "2024-01-30T15:32:07.225Z",
        },
      ],
    },
    {
      id: 8,
      name: "react-components",
      label: "React 组件库",
      createdAt: "2024-01-30T08:59:32.737Z",
      updatedAt: "2024-01-30T08:59:32.737Z",
      lists: [
        {
          id: 39,
          contribute: "https://github.com/mantinedev/mantine",
          desc: "一款功能齐全的 React 组件和 Hook 库，同时支持 Preact",
          home: "https://mantine.dev/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/mantine.svg",
          name: "Mantine",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 35,
          contribute: "https://github.com/ant-design/ant-design/",
          desc: "基于 Ant Design 设计体系的 React UI 组件库，主要用于研发企业级中后台产品",
          home: "https://ant.design/index-cn",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/antd.svg",
          name: "Ant Design",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 37,
          contribute: "https://github.com/mui-org/material-ui",
          desc: "便捷、且易上手的 React 组件库，助你快速搭建网站",
          home: "https://material-ui.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/material.svg",
          name: "Material UI",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 36,
          contribute: "https://github.com/chakra-ui/chakra-ui",
          desc: "Chakra UI 是易上手、模块化且支持无障碍的组件库",
          home: "https://chakra-ui.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/chakra.svg",
          name: "Chakra UI",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 41,
          contribute: "https://github.com/pinterest/gestalt",
          desc: "基于 Pinterest 设计体系的 React UI 组件库",
          home: "https://gestalt.pinterest.systems/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/pinterest.svg",
          name: "Gestalt",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 40,
          contribute: "https://github.com/webeetle/windy",
          desc: "基于 Tailwind 的 React 组件库",
          home: "https://windy-docs.vercel.app/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/windy.svg",
          name: "Windy",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 43,
          contribute:
            "https://github.com/carbon-design-system/carbon/tree/main/packages/carbon-react",
          desc: "基于 IBM Carbon 开源设计体系的 React UI 组件库",
          home: "https://react.carbondesignsystem.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/carbon.svg",
          name: "Carbon Design",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 42,
          contribute: "https://github.com/vechai/vechaiui",
          desc: "基于 Tailwind，且支持无障碍访问的 React UI 组件库，同时拥有酷炫的暗黑主题",
          home: "https://www.vechaiui.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vechai.svg",
          name: "Vechai UI",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 46,
          contribute: "https://github.com/grommet/grommet",
          desc: "基于 styled-components 专注体验设计的 React UI 组件库",
          home: "https://v2.grommet.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/grommet.svg",
          name: "Grommet",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 47,
          contribute: "https://github.com/segmentio/evergreen",
          desc: "开箱即用的企业级 React UI 组件库",
          home: "https://evergreen.segment.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/evergreen.svg",
          name: "Evergreen",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 44,
          contribute: "https://github.com/JetBrains/ring-ui",
          desc: "基于 JetBrains 设计体系的 React UI 组件库",
          home: "https://jetbrains.github.io/ring-ui",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/jetbrains.svg",
          name: "Ring UI",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 48,
          contribute:
            "https://bitbucket.org/atlassian/atlassian-frontend-mirror",
          desc: "基于 Atlassian 设计规范的 React UI 组件库",
          home: "https://atlaskit.atlassian.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/atlaskit.png",
          name: "Atlaskit",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 45,
          contribute: "https://github.com/adobe/react-spectrum",
          desc: "基于 Adobe 设计体系 Spectrum 的 React UI 组件库",
          home: "https://react-spectrum.adobe.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/adobe.svg",
          name: "React Spectrum",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 49,
          contribute: "https://github.com/uber/baseweb",
          desc: "基于 Uber 设计体系的 React UI 组件库",
          home: "https://baseweb.design/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/baseweb.svg",
          name: "Base Web",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 51,
          contribute: "https://github.com/youzan/zent",
          desc: "有赞官方团队基于 PC 端 WebUI 规范的 React 实现，提供了一整套基础的 UI 组件以及一些常用的业务组件",
          home: "https://youzan.github.io/zent/zh/guides/install",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/zent.png",
          name: "Zent",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 52,
          contribute: "https://github.com/react-bootstrap/react-bootstrap",
          desc: "基于 Bootstrap 实现的 React 组件库",
          home: "https://react-bootstrap.github.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/react-bootstrap.svg",
          name: "React Bootstrap",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 50,
          contribute: "https://github.com/react-component",
          desc: "Ant Design 中各个组件的对应实现",
          home: "http://react-component.github.io/badgeboard/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/react.svg",
          name: "React Component",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
        {
          id: 56,
          contribute: "https://github.com/alibaba-fusion/next",
          desc: "Alibaba Fusion Design 企业级的中后台设计系统解决方案",
          home: "https://fusion.design/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/fusion.svg",
          name: "Fusion Design",
          createdAt: "2024-01-30T15:32:07.223Z",
          updatedAt: "2024-01-30T15:32:07.223Z",
        },
      ],
    },
    {
      id: 9,
      name: "standard",
      label: "语言文档和规范",
      createdAt: "2024-01-30T08:59:42.959Z",
      updatedAt: "2024-01-30T08:59:42.959Z",
      lists: [
        {
          id: 24,
          contribute: "https://github.com/tc39/ecma262",
          desc: "ECMAScript 标准",
          home: "https://tc39.es/ecma262/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/ecma.svg",
          name: "ECMAScript",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 26,
          contribute: "https://github.com/mdn/mdn",
          desc: "提供 Web 技术文档，学习 Web 开发的最佳实践",
          home: "https://developer.mozilla.org/zh-CN/docs/Web",
          is_docschina: false,
          logo: "https://docschina-live-10765e.tcloudbaseapp.com/home/logo/mdn-icon.svg",
          name: "MDN",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 29,
          contribute: "https://github.com/microsoft/TypeScript-Website",
          desc: "TypeScript 是带有类型语法的 JavaScript",
          home: "https://www.typescriptlang.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/typescript.png",
          name: "TypeScript",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 30,
          contribute: "https://github.com/WebAssembly/website",
          desc: "WebAssembly（缩写为 Wasm）是一种用于基于堆栈虚拟机的二进制指令格式",
          home: "https://webassembly.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/webassembly.svg",
          name: "WebAssembly",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 31,
          contribute: "https://github.com/dart-lang/site-www",
          desc: "Dart 是一种客户端优化的语言，可在任何平台上实现快速应用",
          home: "https://dart.dev/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/dart.svg",
          name: "Dart",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 27,
          contribute: "https://github.com/rust-lang/www.rust-lang.org",
          desc: "一门帮助每个人构建可靠且高效软件能力的语言",
          home: "https://www.rust-lang.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/rust.svg",
          name: "Rust",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 32,
          contribute: "https://github.com/xitu/graphql.github.io",
          desc: "一种用于 API 的查询语言",
          home: "http://graphql.cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/graphql.svg",
          name: "GraphQL",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 38,
          contribute: "https://github.com/json-schema-org/json-schema-spec",
          desc: "JSON Schema 是一个词汇表，可以验证、注释和操作 JSON 文档",
          home: "http://json-schema.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/json-schema.svg",
          name: "JSON Schema",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 34,
          contribute: "https://github.com/w3c/csswg-www",
          desc: "CSS 规范说明",
          home: "https://www.w3.org/Style/CSS/specs.en.html",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/w3c.svg",
          name: "CSS",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
        {
          id: 33,
          contribute:
            "https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md",
          desc: "OpenAPI 规范为 RESTful API 定义了一个与语言无关的标准接口",
          home: "https://swagger.io/docs/specification/about/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/openapi.png",
          name: "OpenAPI",
          createdAt: "2024-01-30T15:32:07.222Z",
          updatedAt: "2024-01-30T15:32:07.222Z",
        },
      ],
    },
    {
      id: 10,
      name: "test",
      label: "测试工具",
      createdAt: "2024-01-30T08:59:52.161Z",
      updatedAt: "2024-01-30T08:59:52.161Z",
      lists: [
        {
          id: 12,
          contribute: null,
          desc: "Vue Test Utils 是 Vue.js 官方的单元测试实用工具库",
          home: "https://test-utils.vuejs.org/",
          is_docschina: false,
          logo: "https://test-utils.vuejs.org/logo.svg",
          name: "Vue Test Utils",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 14,
          contribute: null,
          desc: "Karma 的主要目标是，让测试驱动开发(TDD)变得简单、快速和有趣。",
          home: "https://karma-runner.github.io/2.0/index.html",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/karma.png",
          name: "Karma",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 17,
          contribute: null,
          desc: "Facebook 开发的零配置测试平台，让代码库更加稳定和健壮",
          home: "https://jest.docschina.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/jest.png",
          name: "Jest",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 16,
          contribute: null,
          desc: "未来的测试运行器",
          home: "https://github.com/avajs/ava",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/ava.png",
          name: "ava",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 18,
          contribute: null,
          desc: "Mocha 是运行在 Node.js 和浏览器上的功能丰富的 JavaScript 测试框架，使异步测试变得简单而有趣。Mocha 串行运行测试，提供灵活精准的报告，同时将未捕获的异常映射到正确的测试用例。",
          home: "https://mochajs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/mocha.svg",
          name: "Mocha",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 23,
          contribute: null,
          desc: "Chai 是一个用于 Node.js 和浏览器的 BDD/TDD 断言库，可以与任何 JavaScript 测试框架便捷配对",
          home: "http://chaijs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/chai.png",
          name: "Chai",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 21,
          contribute: null,
          desc: "用于对 JavaScript 隔离测试 spy, stub 和 mock。适用于任何单元测试框架",
          home: "http://sinonjs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/sinon.png",
          name: "Sinon.JS",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 25,
          contribute: null,
          desc: "一个富于表现力、可读性强、与框架无关，用于 Node.js 的 BDD 风格断言库",
          home: "https://shouldjs.github.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/docschina.png",
          name: "Should.js",
          createdAt: "2024-01-30T15:32:07.220Z",
          updatedAt: "2024-01-30T15:32:07.220Z",
        },
        {
          id: 19,
          contribute: null,
          desc: "Puppeteer 可以通过 DevTools 协议控制 headless Chrome 或 Chromium",
          home: "https://pptr.dev/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/puppeteer.png",
          name: "Puppeteer",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 28,
          contribute: null,
          desc: "生成随机数据，拦截 Ajax 请求",
          home: "http://mockjs.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/mockjs.svg",
          name: "Mock.js",
          createdAt: "2024-01-30T15:32:07.220Z",
          updatedAt: "2024-01-30T15:32:07.220Z",
        },
        {
          id: 20,
          contribute: null,
          desc: "Jasmine 是一个用于测试 JavaScript 代码的行为驱动开发(BDD)框架",
          home: "https://jasmine.github.io/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/jasmine.png",
          name: "Jasmine",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
        {
          id: 22,
          contribute: null,
          desc: "expect 帮助你编写更好的断言",
          home: "https://github.com/mjackson/expect",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/docschina.png",
          name: "expect",
          createdAt: "2024-01-30T15:32:07.219Z",
          updatedAt: "2024-01-30T15:32:07.219Z",
        },
      ],
    },
    {
      id: 11,
      name: "visualization",
      label: "可视化工具",
      createdAt: "2024-01-30T09:00:02.489Z",
      updatedAt: "2024-01-30T09:00:02.489Z",
      lists: [
        {
          id: 96,
          contribute: null,
          desc: "使用 JavaScript 实现的开源可视化库",
          home: "http://echarts.baidu.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/echarts.png",
          name: "ECharts",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 99,
          contribute: "https://github.com/docschina/threejs.org",
          desc: "JavaScript 3d 库",
          home: "https://threejs.docschina.org/",
          is_docschina: true,
          logo: "https://cdn.docschina.org/home/logo/threejs.png",
          name: "Threejs",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 98,
          contribute: null,
          desc: "跨平台的轻量级 2D 渲染对象模型",
          home: "http://spritejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/spritejs.png",
          name: "SpriteJS",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 100,
          contribute: null,
          desc: "一套基于可视化编码的图形语法，以数据驱动，具有高度的易用性和扩展性",
          home: "https://antv.alipay.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/antv.svg",
          name: "G2 可视化图形语法",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 93,
          contribute: null,
          desc: "基于全新一代数据可视化解决方案 AntV",
          home: "https://antv.alipay.com/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/antv.svg",
          name: "AntV 可视化解决方案",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 101,
          contribute: null,
          desc: "G6 是解决流程图和关系分析的图表库",
          home: "https://antv.alipay.com/zh-cn/g6/1.x/index.html",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/antv.svg",
          name: "G6 关系图类库",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 102,
          contribute: null,
          desc: "面向移动端的一套基于可视化图形语法的图表库，具有精简、高性能、易扩展的特性",
          home: "https://antv.alipay.com/zh-cn/f2/3.x/index.html",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/antv.svg",
          name: "F2 移动端图表库",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 107,
          contribute: null,
          desc: "基于 Vue 和 ECharts 封装的图表组件",
          home: "https://v-charts.js.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "v-charts",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
        {
          id: 106,
          contribute: null,
          desc: "一个遵循 Web 标准，用于可视化数据的 JavaScript 库",
          home: "https://d3js.org.cn/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/d3.svg",
          name: "D3.js",
          createdAt: "2024-01-30T15:32:07.251Z",
          updatedAt: "2024-01-30T15:32:07.251Z",
        },
      ],
    },
    {
      id: 12,
      name: "vue",
      label: "Vue",
      createdAt: "2024-01-30T09:00:12.823Z",
      updatedAt: "2024-01-30T09:00:12.823Z",
      lists: [
        {
          id: 104,
          contribute: "https://github.com/vuejs/vue-cli",
          desc: "Vue.js 官方指定的脚手架工具",
          home: "https://cli.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "vue-cli",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 109,
          contribute: "https://github.com/vuejs/devtools",
          desc: "用于调试 Vue.js 应用程序的 devtool 扩展",
          home: "https://devtools.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue-devtools.svg",
          name: "vue-devtools",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 103,
          contribute: "https://github.com/vuejs/vue-router-next",
          desc: "Vue 3 官方路由",
          home: "https://next.router.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vue Router v4",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 108,
          contribute: "https://github.com/vuejs/vue-router",
          desc: "Vue 2 官方路由",
          home: "https://router.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vue Router v3",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 110,
          contribute: "https://github.com/vuejs/vuex",
          desc: "Vue 官方状态管理工具",
          home: "https://next.vuex.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vuex",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 111,
          contribute: "https://github.com/vuejs/vetur",
          desc: "为 Vue 2 量身打造的 VSCode 插件",
          home: "https://vuejs.github.io/vetur/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vetur",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 105,
          contribute: "https://github.com/johnsoncodehk/volar",
          desc: "为 Vue 3 量身打造的 VSCode 插件，需禁用 Vetur",
          home: "https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Volar",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 112,
          contribute: "https://github.com/vuejs/jsx-next",
          desc: "Vue 3 的 JSX 插件",
          home: "https://vue-next-jsx-explorer.netlify.app/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Vue JSX Next",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 113,
          contribute: "https://github.com/vuejs/composition-api",
          desc: "在 Vue 2 中使用 Composition API",
          home: "https://composition-api.vuejs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/vue.svg",
          name: "Composition API",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
        {
          id: 114,
          contribute: "https://github.com/nuxt/nuxt.js",
          desc: "基于 Vue.js 的一站式解决方案",
          home: "https://zh.nuxtjs.org/",
          is_docschina: false,
          logo: "https://cdn.docschina.org/home/logo/nuxt.svg",
          name: "Nuxt.js",
          createdAt: "2024-01-30T15:32:07.252Z",
          updatedAt: "2024-01-30T15:32:07.252Z",
        },
      ],
    },
  ],
}
